import type { SentencePair } from "./text-sample";

// Supplied Japanese originals and English translations from Jordan Niver-Johnson.
// Page-sized chunks preserve the full drafts while keeping the reader comfortable.
export const jordanSubstituteForFictionPairs: SentencePair[] = [
  {
    "original": "いつだって冬は寒い。今年の冬は例年よりさらに寒かった。デパートの外商が持ってきたハイブランドのコートを冷たい風にはためかせ、クリスマスに向けて美しく飾られた表通りを私は歩いていた。コートの色はスモーキーピンク。今季の人気カラーらしい。\n\n黒いロングヘアが風にはためきひらひらと揺れる。顔にかかった髪を退しりぞけて、私は表通りから一本入った道へと進路を変え、歩いていった。\n\n庶しょ民みん的な店がぽつぽつと並ぶ一角まで来て、私はカラカラと鈴を鳴らして目的のガラス扉を押し開いた。\n\n待ち合わせ場所に指定した喫きっ茶さ店てんへ入り、一人ですと店員に告げる。空すいている店内で、お好きな席へどうぞと返され、私は通路に置かれたラックから適当に新聞を取り窓際の席へと向かった。かつかつと、履はいているハイヒールの音が鳴る。足にぴったりフィットするようにオーダーメイドした逸品だ。\n\n今日は薄うす化げ粧しょうをしている。淡い色の口紅に、ブラウンのアイシャドウ。年齢のわりに大人びた格好をしているのは、今日が特別な日だからだ。",
    "translation": "Winters are cold regardless of when they occur. And this one was colder than most which preceded it.\n\nI was walking down some street- one which was adorned with beautiful decorations that spoke of a Christmas to come. I wore a high-fashion coat which a designer had brought to an exhibition in our home. It was flapping in the cold wind as I walked. The coat was a smokey, pinkish color- apparently this season’s trendy shade of choice.\n\nMy long black hair flowed in strands in the wind. Brushing back a few tangles from my face, I left the main thoroughfare in favor of a side street as I continued to walk along.\n\nComing to the end of a block of modest looking shops, I pushed through the glass door entryway of my destination- setting the shop bell tinkling as I entered.\n\nI entered the café that we had planned to meet at and said to the hostess, “Table for one please,” pointing to the vacuous collection of chairs.\n\n“Please sit where you like,” came her response.\n\nI absentmindedly extracted a newspaper which was hanging on a shelf on the wall and made my way to a seat by the window. My high heels made a click-clack as I went. They were custom and fit my feet to perfection.\n\nToday, I was fairly dolled up. Pale lipstick and brown eye shadow.\n\nThe explanation for my rather adult get up was simple. Today was a special day.\n\nThis café was just a run of the mill chain diner. Not some quaint little hipster hole in the wall. Just a common shop with manga and sports magazines abundant and readily available."
  },
  {
    "original": "なんてことないチェーンの喫茶店。小こ洒落じゃれたカフェとは違い、漫画やスポーツ新聞が置いてある庶民的な店だ。\n\n窓に面したカウンター席について一応メニューを開き確認してみるが、特にリニューアルされた様子はなく、いつもと変わりなかった。コーヒー、紅茶、それから様々なアレンジドリンク。\n\n近くを通りかかった店員にホットコーヒーを頼み、鞄かばんから古びたノートを取り出した。本当は紅茶の方が好きなのだけれど、と思いながらノートをめくる。\n\n丁てい寧ねいに扱わなければページがバラバラになってしまいそうなほど使い込まれたノート。三分の二ほど使われたそれは、日記帳だ。\n\nその年の日記帳を鞄に入れて、私はいつも持ち歩いていた。革の表紙がついた立派なノートだ。使い込まれた革は、手によく馴な染じむ。白紙になる手前のページは、二日前の日付で止まっていた。私は何度も読み返したそこを、もう一度読み始めた。\n\n『だいぶ寒くなってきた。制服のスカートだと脚が冷たくなるけど、まだ自転車で通学する。お母さんは送迎の車を出すって言うけど、こうして自転車に乗って、景色を見ながら体を動かすのが好き。",
    "translation": "From my place at the counter closest to the window, I went ahead and checked the menu, but it hadn’t changed much and looked the same as always. It had coffees, black tea, and various beverage offerings listed on it.\n\nI caught a waitress as she went buy and ordered a hot coffee, as I drew an old and well-worn notebook out of my leather bag.\n\n...I would have preferred the black tea though…I thought as I flipped through the pages.\n\nA victim of years of heavy use, the notebook itself would have probably fallen apart if I didn’t handle it nicely. All of the pages of the diary were used up besides the last third or so.\n\nI always brought the diary -of any given year- along with me when I was out and about. It really was a fine notebook, with a leather skin cover to boot. The well-worn leather felt smooth and inviting to the touch. I flipped to the part of the diary where the used pages reverted to white. A page before this was the last entry. A dated entry two days prior.\n\nI started to read the passage which I had read over and over again, for many years.\n\n“It’s gotten fairly chilly lately. The skirt from my school uniform doesn’t quite cut it lately in terms of warmth… but I am still going to school by bike. Mom said she would send the family car to pick me up from school, but I prefer my bike. I like the scenery and moving my body."
  },
  {
    "original": "もうすぐ期末テストだから、たくさん勉強することがある。お父さんはまた学年一位を期待してるみたいだけど、順位はどうでもいい。学ぶことが楽しい。\n\n最近は特に、世界史が好き。ヨーロッパ史だけじゃなくて、アメリカ史、中国史、各地の歴史を学ぶと地理や天候に関することにも興味が湧くし、不思議な共通点があったりしてとても楽しい！\n\n今日も本屋さんに寄って歴史の本を一冊買おうと思ったけど、明後日は誕生日パーティ。明日のうちにテストの勉強を片付けておかないと。いつもの喫茶店でコーヒーを飲んで、勉強して帰ろう。あそこが一番落ち着く。\n\nまだ少し早いけど、今日はもう寝よう。明日からはさらに忙しい。』\n\n読み終えて、私は周りの人に不審がられない程度に、ほんの少しだけ笑みを浮かべた。\n\nそこには何の変哲もない日常が描かれているだけだったが、そこから先の白紙部分が、私にとって最も重要だったのだ。",
    "translation": "I have loads to study as the term final is right around the corner. Dad seems to expect me to finish at the top of my class this year too, but I honestly could care less about where I end up. What I really enjoy is learning.\n\nLately, world history has become a particular favorite of mine. Not just European history but American, Chinese, and history from all around – not to mention marveling at these places and their unique geographies and climates…and all the mysterious things they have in common with one another!\n\nToday, I just went to a bookshop to buy a new history book, but the day after tomorrow is my birthday party. Gotta get all the studying I have to do out of the way tomorrow!\n\nI think I’ll just go to my favorite coffee shop, drink coffee, study and then head home. That place always makes me feel so calm.\n\nIt’s still a bit early but I think I might head to bed. Tomorrow is going to be even more busy.”\n\nAs I finished reading, I smiled wryly – containing myself enough so that no one thought that I was up to something.\n\nThese last pages of the diary- which only contained the most common days from a common life- were to me particularly important- if only for the white, blank pages that they preceded."
  },
  {
    "original": "ノートを鞄にしまい、私は持ってきた新聞を開いた。\n\n待ち合わせ時間まであと少し。パラパラとあてもなく新聞をめくっていたら、読者投稿欄らんの記事が目に留まった。\n\n『我が家のクローン事情』\n\nペットのクローン技術が一般に普及して随ずい分ぶん経ちます。\n\n我が家でも、保存していたペットの細胞から死んでしまった文ぶん鳥ちょうのクローンを再生することにしました。\n\n去年、息子が可愛かわいがっていた文鳥が病気で死んでしまいました。名前はぴーすけです。よく、ぴーすけぴーすけ、と人の声を真似まねてさえずりました。\n\n動かなくなったぴーすけを見て途方にくれる息子に、私は声をかけることができませんでした。小学校に入学したばかりの子供に、死という概がい念ねんは難しすぎました。\n\nクローン再生した雛ひなのぴーすけを連れて家に帰ると、息子は喜びました。ぴーすけだ！　と叫んで私の手から鳥とり籠かごを受け取り、その日から大切に世話をしました。",
    "translation": "I put the notebook away and started to leaf through the newspaper I had picked up.\n\nI still had time to kill before they picked me up.\n\nAs I fanned through the pages randomly, I came to the “Stories from our readers” section and my eyes were drawn to an article:\n\n“Clones and their impact on our household”\n\nWe have long since gotten used to the ability to clone our pets once they have died. In our family too, we cloned our pet finch from cells we had saved after it passed away.\n\nLast year, the finch that my son had adored so much passed away from some disease. His name was “Hee-Hoo” and one of his favorite past times was to imitate people’s voices as he warbled along.\n\nAfter Hee-Hoo died, as my son looked down at the lifeless body - I had had no words I could say to comfort him. He had just entered elementary school, and at his age I could tell that death was too difficult a concept to grasp.\n\nMy son was so happy when I brought the small chick, the “Hee-Hoo clone” home.\n\n“Hee-Hoo!” He shouted and took the cage carefully in his hands.\n\nFrom then on, he took care of this ‘new’ Hee-Hoo with exceptional tenderness.\n\nThe birds coloring and shrill squeaks were the exact same as the old Hee-Hoo.\n\nWhen male finches lose their chick feathers and grow in their adult ones, however, each individual makes an original song and starts warbling. And the Hee-Hoo clone eventually started to go through this same transformation. It was all my son could do to contain himself while he waited to hear Hee-Hoo’s warbling again."
  },
  {
    "original": "羽の色も鳴き声も、かつてのぴーすけと同じでした。\n\nオスの文鳥は、雛の羽が抜けて大人の羽に生え変わると、それぞれの個体ごとにオリジナルソングを作り、さえずり始めます。クローンのぴーすけにもその時期がやってきました。息子は、ぴーすけがいつさえずり始めるのかと、毎日首を長くして待っていました。\n\nある日、息子が学校に行っている間に、ぴーすけがさえずり始めました。ぴっぴー、ぴっぴー、と目覚まし時計を真似したようなさえずり方でした。\n\n私は学校から帰ってきた息子に、ぴーすけがさえずり始めたことを話しました。\n\nすると息子は喜び、ぴーすけを籠から出して腕にとまらせ、さえずるのを待ちました。\n\nぴっぴー、ぴっぴー、とさえずり始めたぴーすけを見て、息子は顔を曇らせ、ぴーすけを腕から払い落としました。ぴーすけは羽ばたきましたが、床に落ちてしまいました。\n\n今まで大切に育ててきたぴーすけです。私は息子の行動に驚きました。\n\n「何するの！」\n\n「お母さん、こいつぴーすけじゃないよ！　だってぴーすけぴーすけ、って言わないもん！」",
    "translation": "One day, when my son was at school, hee-hoo started to warble.\n\n“Hee-Heee” “Hee-Heeee”\n\nIt was clear that he had picked this up from the alarm on my bedside clock.\n\nAs soon as my son got back from school, I told him about Hee-Hoo’s first warbles.\n\nAlmost at once, my son went to his cage, pulled him out and set him on his arm, and waited for the first of these new warbles to come.\n\nHee-hoo finally started to sing.\n\n“Hee-Heeeee” “Heee-Heeee”\n\nMy son’s face clouded over immediately. He then proceeded to sweep “Hee-Hoo” off his arm and onto the floor, to which -though he tried to adjust his wings in time- “Hee-Hoo” ended up falling with a soft thump.\n\nI had never seen my son treat Hee-Hoo this way, so I was stunned by this sudden outburst.\n\n“What are you doing?!”\n\n“Mommy, this is not “Hee-hoo!” He can’t even say ‘hee-hoo,’ anymore!”\n\n“Even so… Look at him sweetie. He looks exactly like ‘Hee-Hoo’.”\n\n“He’s not him. He just can’t be!”\n\nAfter that, my son totally avoided “Hee-Hoo.” To the point where my husband and I decided that we would give “clone Hee-Hoo” a totally new name and try to raise him normally. At the same time, we explained to our son that this new finch was just a spitting image of Hee-hoo but actually a different bird, and most importantly that we were sorry for making him upset and confused about it all."
  },
  {
    "original": "「そんなこと言ったって、ぴーすけと同じ姿でしょ？」\n\n「でも、違う。絶対に違うよ！」\n\nその後息子はぴーすけに近づこうとしませんでした。私と主人は話し合って、クローンのぴーすけに全く別の名前をつけて飼うことにしました。その際、息子にはこの文鳥はぴーすけのそっくりさんで、実はぴーすけではないことを説明し、勘違いさせてしまったことを謝りました。\n\n今では息子と文鳥は仲良く暮らしています。小学校二年生になった息子は、ぴーすけのお墓を作りました。\n\nクローン技術には賛否両論あるかと思います。ですが我が家では、ペットの細胞を冷凍保存してクローンとして再生することは、二度とないでしょう。\n\nＰ．Ｎ桜文子さん（37）主婦\n\nちょうど記事を読み終わった時、こちらに近づいてくる足音がした。\n\n「お待たせ」\n\n「お父さん」\n\n私はにっこりと笑って、残っていたコーヒーを飲み干した。好きではない苦味と酸味が口に残る。ああ、好きじゃない。むしろ飲みすぎて嫌いになった。",
    "translation": "Now, our son gets along well with this new finch. And when he entered second grade, he even had the wherewithal to build a grave for the late “Hee-Hoo” in our back yard.\n\nThere are opinions across the board about the ethics of cloning. But in our family, I doubt we will ever try to clone an animal again in the future.\n\nP.N Fumiko Sakura (37) Housewife\n\nJust as I was finishing the article, I heard footsteps approaching where I sat.\n\n“Sorry for keeping you waiting, sweetie.”\n\n“Hey dad.” I flashed a smile in his direction and drank down the rest of my coffee. The after taste left a dreadful and tannic bitterness in my mouth. Yuck, I really don’t like this stuff…I just have drunk it so much now that I couldn’t not hate it… i thought.\n\n“Shall we get a move on? Your mom’s waiting out in the car.”\n\nMy dad scooped up the bill and started walking over the register. As he presented the clerk with a jet-black credit card to pay, I slotted the newspaper back into its original spot on the shelf.\n\n“The restaurant I picked for us tonight is a bit fancier than usual. It’s your birthday after all; a bit of luxury sounds fitting.”"
  },
  {
    "original": "「行こうか。母さんは車で待っているよ」\n\n父は伝票を手に取ると、レジの方へ歩いていった。黒いクレジットカードで支払いを済ませているのを横目に、私は新聞を元の棚たなに戻す。\n\n「今日はいつもより良いレストランに行くよ。お前の誕生日だからな、豪勢にいこう」\n\n店の外につけられた黒い車には、いつもよりおしゃれをした母が乗っていた。白手袋をした運転手がドアを開けてくれ、私は後部座席へと乗り込む。隣に座る母が、私を見て言った。\n\n「もっと良い喫茶店を使っていいのよ。ホテルのラウンジでもいいわ」\n\n「ここのお店が好きなの」\n\nはにかんでそう答え、私は助手席の父を見た。父は振り向いて朗ほがらかに笑い、顔の皺しわを深くさせた。\n\n「はは、中学生の時から変わらないな。いつもここで勉強していた」\n\n私の年にしては随分と年齢が高い両親だと、周りからは思われることだろう。実際にそうだ。\n\n緩ゆるやかに車が発進する。何不自由ない生活と、「私」を愛してくれる両親。",
    "translation": "My mom was in her usual spot, already seated- and exuding class- in the back of the sleek black car parked out front of the shop. Our white gloved driver opened the door for me, and I climbed into the back seat. My mom looked over from her seat and said, “I still don’t know why you insist on coming to this place, dear. Wouldn’t the lounge in the hotel be more…appropriate?”\n\n“I just have a thing for this place. It’s that simple.” I answered through gritted teeth, pivoting towards my dad in the front seat.\n\nMy dad was smiling cheerfully as he looked back at us, the lines of his face ripe with emotion.\n\n“Hahm, you haven’t changed a bit since middle school. You were always studying here back then too.”\n\nFrom the outside looking in, my parents must seem to be quite old- too old- to be my mom and dad.\n\nAnd in actuality, they are.\n\nThe car set out gently from the curb- just me and my loving parents who lived this luxurious life without wanting anything.\n\nAs I looked outside the window at the evening scenery rolling past, I stroked the leather bag that I had carried with me at all times. The frame of the notebook within it felt hard to the touch.\n\nThe journal that “I” had kept until “I” was 17. And now I had read it over and over again whenever I had the chance.\n\n“I can’t tell you how happy I am to be celebrating your 18th, sweetie.”"
  },
  {
    "original": "窓の外を流れる夜景を見ながら、私はいつも持ち歩いている鞄を撫なでた。中身のノートが手に硬い感触を残す。\n\n「私」が十七歳までつけていた日記帳。暇があれば私は一人でこのノートを読み返す。\n\n「こうして十八歳の誕生日を祝えて幸せだよ」\n\n「ありがとう、お父さん。私もよ」\n\n裕福な両親の元に生まれ、某ぼう有名小学校に入学。小学校三年生の時ピアノコンクールにて優勝。中学進学後はバレーボール部に所属、全国大会で優勝。高校入学後は勉学に専念し、学年トップを維持。そして高校二年生、十七歳最後の日。\n\n下校中に居眠り運転の車に撥はねられ、誕生日前日に彼女はその生しょう涯がいを終えた。\n\n「長かったわね……」\n\n母が誰にともなくしみじみと呟つぶやく。父はその言葉を聞かなかったふりをして、立派なスーツの袖そでから覗のぞく高級な腕時計を見た。\n\n「少し遅くなってしまったな……ディナーを楽しもう」\n\nレストランまでは少し距離があった。車内で母が話しかけてくる。\n\n「その口紅もアイシャドウもよく似合っているわね。たくさん試した甲斐かいがあったわ」",
    "translation": "“Thanks, dad. Me too.”\n\n“I” was born to well-to-do parents and went to some famous elementary school. When “I” was in third grade, I won my first piano recital. After entering junior high school “I” joined the volleyball team, and we won the national tournament. After entering high school, “I” dropped everything to focus exclusively on my studies, and was the top of “my” year. Then, when “I” was a junior, and on my last day as a seventeen-year-old-\n\n-as “I-that girl” made my way home from school, I was struck and hit by a driver who had fallen asleep at the wheel- breathing “my” last breath there on the pavement.\n\n“It has taken so long to get here…”, my mom said to herself melancholically, without directing her words to anyone in particular.\n\nMy dad pretended that he hadn’t heard this and peered down into the face of his fine wristwatch, which peered out from the gap between his wrist and his fine suit. “Yeah, I guess we’ve been held up a bit…. all the more reason to enjoy a fancy meal.”\n\nThere was still quite a way to the restaurant.\n\nFrom her perch in the backseat, my mother said to me.\n\n“That lipstick and eyeshadow suit you so well, dear. Guess it was worth testing out as many as we did.”\n\n“So true! Just looking through them all was such a treat. I feel a bit selfish for making all the choices, though.”"
  },
  {
    "original": "「そうね、お母さん。選ぶのも楽しかったわ。我わが儘ままを聞いてくれてありがとう」\n\n私はニコッと笑って隣の母を見る。いつもは外商経由だが、今回はデパートまで出向いて、わざわざカウンターで購入したのだ。一般客の少ない時間帯だったからゆっくり見て回れて、とても……\n\nとても、苦痛だった。\n\n化け粧しょう品ひんを用意しましょうと母に言われたとき、「彼女」ならどうするかを真っ先に考えた。この出来事は日記にはなかった。おそらく「彼女」は自分で選びたいと言う。それも、なるべくたくさんある中から。\n\n「お母さん、私デパートに行って選びたい」\n\n母は驚いたようだったが、すぐに「あなたらしいわね」と笑ったので、正解を選べてよかったと心の底から安あん堵どした。\n\n色選びも大変だった。「彼女」が好きな色はピンク。しかし、化粧品でピンクなんて選せん択たく肢しが多すぎる。\n\nこういうときは母を利用するのがいいと、私は学んでいた。",
    "translation": "I smiled dolefully and looked over at my mom. Usually, we would just have vendors or designers come to our house with new products, but yesterday we had actually gone out to a department store together- making our selections directly from the store counter. It had been during the off hours so we could look around at our leisure-it had been such a, such a-\n\n-A total and utter pain in the ass.\n\n“Let’s make sure you have some makeup,” my mom had said. After which I went straight to the thought, what would ‘she-the other I’ do?\n\nThis occurrence had not been written in the diary. And if it had I think “she” would have insisted on… “picking it out myself,” what’s more, “…with as many options as possible.”\n\n“I’d like to pick something out at the department store,” I had said.\n\nMy mom had flashed me a surprise glance, but said, “Well that’s new.” And laughed.\n\nI was relieved that I had chosen the “right” answer.\n\nSelecting the “right” colors had presented another tricky challenge.\n\n“Her” favorite color had been pink. But the sheer number of pinkish options available at the shop was staggering. I soon learned, however, that my mother’s memory could be subverted to solve the problem.\n\n“Mom, which is your favorite between these two?”\n\n“Let’s see…This one perhaps.”\n\nShe had chosen the pale pink option I brought over to show her."
  },
  {
    "original": "「お母さん、これとこれだとどっちがいいと思う？」\n\n「そうねぇ……こっちかしら」\n\n母が選んだのは、二つ持っているうちの淡いピンク色の方だった。\n\n「じゃあ、リップはこれにする。あとはアイシャドウだね」\n\n「何色がいいかしらね」\n\n母はすごく楽しそうだ。期待を裏切らないように振る舞わないといけない。\n\n「お母さんのおすすめの色はある？」\n\n「ブラウンね。目元が上品に見えるわよ」\n\nそう言う母の目元はブラウンだった。こういうのは指摘していかないと。\n\n「お母さんも今日、ブラウンのアイシャドウだね」\n\n「そうなの！　お気に入りの色なのよ、これ」\n\n「じゃあ、私もブラウンにしようかな」\n\nそして、ベーシックな色ゆえにブラウンも数が多い。母に聞くという手法でなんとか化粧品選びをした私は、くたくたに疲れて帰宅した。\n\n父が連れてきてくれたのは、超がつくほど高級なフレンチのフルコース。きちんとテーブルマナーを守ってそれをいただき、私は両親とのディナーを楽しんだ。これは私にとって特別なディナーだ。",
    "translation": "“Alright, I’ll go with this for my lips and now we just have to pick out the eye shadow.”\n\n“We’ve got to find one that fits you just so.”\n\nMy mom seemed like she was having a great time, and I was certain that I had to keep her floating and tread carefully.\n\n“What color do you think would work, mom?”\n\n“It’s got to be brown, dear. It makes your eyes look so refined!”\n\nShe had said, her eyes looking out from the same brown frame. This suggestion, too, would have to be taken very seriously.\n\n“Mom.” I said, gesturing playfully to her eyes.  “It seems like someone else is a fan of brown eyeshadow, too!”\n\n“I had almost forgotten I had it on. Well, yes. It’s my go to color.”\n\n“Hmm, I guess I will have to give it a try, too.”\n\nAnd here again, since brown was such a basic color, there was now a hornet’s nest of colors to choose from.\n\nBy the time we had finally made it home, I was completely exhausted from probing my mom to find all the right shades and colors.\n\nMy father chose a French restaurant of the highest quality for our dinner. So, I had to mind my manners accordingly.\n\nAll in all though, I ended up having a delightful dinner with my parents. And a singularly important one for me.\n\nFor the last 18 years, I had walked in the shadow of “her” traces. More precisely it had been 17 years and 364 days."
  },
  {
    "original": "十八年間、彼女の形跡をたどって生きてきた。正確には十七年と３６４日だ。物心ついた時にはひたすら彼女の日記を読み、彼女の好みを把は握あくし、彼女の歩んだ人生をそっくり模も倣ほうした。両親がそれを求めていることを、幼い頃に私は知った。\n\n彼女の形跡を辿たどることは、唯一の生きるすべだった。\n\n小学生になりたての頃、両親が言い争う声で目が覚めたことがある。あの日のことは忘れられない。\n\n暗い廊ろう下かの先、明かりの付いたリビングのすりガラスの扉越しに、二人の声が聞こえてきた。\n\n「あの子、全然英語ができないのよ。見て、この点数！　やっぱり失敗だわ」\n\n抑え気味な、しかし感情的な母の声がする。私はリビングから少し離れた闇の中で足を止めた。\n\n「そんなことを言うな…まだ可能性はある」\n\n少し疲れたような父の声が答えた。\n\n「作り直すべきよ」\n\n「無理だ、もう前回みたいに処理はできない……二回目は怪しまれる。それに、育て上げるまでに何年かかると思う？　俺たちの年齢を考えろ」\n\n「でも……」",
    "translation": "Ever since I can recall, I have been reading her diary voraciously. Memorizing her likes and replicating her life trajectory. I had learned of my parent’s “expectations” when I was still a young child.\n\nLearned that following in her footsteps was -to me- a matter of survival.\n\nShortly after I had entered elementary school, I recall being woken up by an argument my parents were having. I don’t think I’d ever be able to forget it.\n\nMy parents raised voices had come trickling down the dark hallway- from beyond the frosted glass sliding door to the living room.\n\n“That child is absolutely terrible at English. Look at this score! I knew this wouldn’t work!”\n\nMy mom’s voice was choked by a handful of barely reigned in emotions. I had stopped dead in the hallway – detached in the dark outside the living room.\n\n“Don’t say that…it’s still too early to tell what she’s capable of.”\n\nMy father had answered in an exhausted voice.\n\n“We should make another one!”\n\n“You know that’s impossible. It wouldn’t be as easy to sweep under the rug as last time…twice makes it seem like a pattern-looks too suspicious. Think about it! How many years would we lose raising her back up from scratch? Think about our age!”\n\n“But...I…”\n\nBreath held and shaking, I had returned to my room- arms cradled around myself. If my parents knew I had heard everything…I was certain that would be it for me."
  },
  {
    "original": "私は息を止めて、震える体を自分の腕で抱き締めながら部屋に戻った。ここにいることが両親に知れたら、終わりだと思った。\n\n幾度となく聞かされた思い出話と、渡された日記帳。この時までその重要性を理解していなかった自分の愚かさに、今更ながら気づいた。\n\n彼女にならなければ、彼女を演じきらなければ消される。ひとつ前の「私」は消されたのだ。\n\nそれまで己の思うがままに生きてきた。早期教育とやらで通わされている英語教室は好きでなかったからあまり勉強しなかったし、食べ物の好みも素直に告げてきた。しかし、それはとても危険なことだったのだ。\n\n静かに部屋へ戻り、机のスタンドを一番暗くして付けて、私は引き出しに仕舞ったままだった日記帳を取り出した。そして、そのまま夜が明けるまで読み耽ふけった。読めない漢字はすぐに調べて読み進めた。\n\n彼女の考えていたこと、将来の夢、好きなこと、嫌いなこと、その日やっていたこと、小学校での生活、中学生になってからの部活、高校生になってからの過ごし方。",
    "translation": "Up until this point I had been regaled with “her” stories and had read about “her” in the diary they had given me.\n\nBut I had finally realized -and I can’t believe how stupid I had been not to realize this until then- the tenuousness of my role as their daughter.\n\nI had to become “her,” to play “her” to perfection, or else, be erased. Just as the previous “me” had been.\n\nUntil that point, I had lived as selfishly as any kid would. I didn’t care much for the “advanced placement” English language school they had stuck me in, and I hadn’t held back when it came to telling them my favorite foods. But these behaviors, all of the sudden, had become extremely dangerous.\n\nI had gone back to my room quietly, setting the light on my desk stand to dim.\n\nI took out the diary which lay neatly in the desk drawer and proceeded to study it intensely until dawn. Whenever I came to a word too advanced for me, I would stop and look it up, before picking the diary back up and reading onward.\n\nI poured over her thoughts, her dreams for the future, her favorite things, what she had done each day, her elementary school days and her club sports during junior high, and finally how she spent her days in high school.\n\nLike a character whose shoes I was stepping into, I drilled the words in the diary into my head like lines of a play. And then, I did my best to actually play the part."
  },
  {
    "original": "台本を読む役者のように、全てを頭に叩き込んだ。そして、必死でそのように振る舞った。\n\nピアノコンクールで優勝するために、どれだけ練習しただろうか。ピアノの先生には熱心だと褒ほめられたが、命がかかっていれば誰だって熱心になるだろう。\n\n中学生のとき、バレーボール部が全国大会で優勝できたのは偶然だった。さすがにチーム競技をコントロールすることはできないし、この年齢になってしまえば、「消される」ことはないだろうと思っていた。両親も高齢になってきたからだ。しかし油断はできない。味方は誰もいないのだから。\n\n日記の試練は小学校から始まっていた。小学校の算数のテストが満点ではなかった、と言って号泣したというエピソードが書いてあったからだ。\n\nまず、日記帳の日付に近い算数のテストで一問だけ間違える。テストの答案が返ってきたあとは、子役並みの演技をしなくてはいけなかった。\n\n泣くときは、悲しいことや怖いことを想像しながら……悲しいこと……怖いこと……",
    "translation": "I wonder how much I had ended up practicing so that I could win that piano recital. The teacher applauded me for being so dedicated, but if your life was on the line I feel like anyone would have done the same.\n\nIn junior high, the fact that my team did end up winning the national tournament was a complete fluke. It was obvious to me that I wouldn’t be able to dictate the course of a team sport, and besides, I comforted myself with the thought, now that they’re so old, there’s no way they’d erase me....\n\nThey truly had become elderly by then, but I still didn’t let my guard down completely. The reason being, I had no one around me I could truly rely on.\n\nThe first tricky performance of the diary happened in elementary school.\n\nThe script: a key episode was written during which “I” had come home in tears because I hadn’t gotten a perfect score on a math test.\n\nFor this purpose, I chose a math test close to the diary date in question, and I got just one answer on it wrong. And after that test was passed back to me graded in class, I knew I had to play my role as “crying child”- and play it to the t.\n\nWhen I was crying, I remember thinking, something terribly sad is happening, something terrifying…a terrible thing…so terrifying…"
  },
  {
    "original": "私は、自分が「始末」される光景を想像して母の前でわんわん泣いた。\n\n「次のテストで頑張りましょう」\n\n母はそう言って私の頭を撫でた。少しホッとしたように見えたのは、かつての「彼女」も同じように泣いたことがあるからだろう。\n\n中学生のときは部活と勉強の両立が大変だった。全国大会常連校なので練習は厳しく、時間も取られる。しかし、そんな中でも「彼女」は成績上位をキープし続けていた。私はいつも眠い目をこすりながら必死で勉強していた。一体彼女はどんな状態で勉強していたのだろう？　彼女をトレースすればするほど、その胆たん力りょくに感かん嘆たんした。\n\n高校生活で学年一位を維持することは、大変だったけれど自分一人の力でできることだったから、バレーボール部の大会ほど運に左右されることはなかった。ただ、トップレベルの進学校なので、バレーボールと同様にハードではある。でもそれは、「彼女」の頭脳が優秀なおかげでかなり助かった。「私」は記憶力も理解力も抜ばつ群ぐんにいい。",
    "translation": "An image of myself being “disposed of” by my parents flashed inside my mind as I bawled in front of mom.\n\n“Just do your best on the next one, ok dear?”\n\nMy mom said as she stroked my head. A look of relief seemed to be playing across her face- a side effect of a recollection perhaps”? A time when “she” had cried in the same way.\n\nIn junior high school, it was quite a task to keep the two plates of academics and sports spinning. It was a school that had become accustomed to national championships, so the practices were intense, and ate into my schedule. But during that same period “she” had kept her same top-tier grades. I spent my days rubbing my bleary eyes as I fought to keep apace. How had “she” pulled all this off and in what condition? As I continued to trace the contour of “her” character I became more and more impressed by “her” grit.\n\nHolding the top position in class in high school hadn’t been easy, but it was a solo activity. So, compared to the volleyball tournament, nailing this performance didn’t hinge so much on sheer luck. Nonetheless, I did have my heart set on top level colleges so achieving the top place in class was at least as hard as volleyball had been.\n\nBut thankfully, I had the advantage of “her” remarkable brain to help me through it all. “Her”-no-my powers of comprehension and memory are undoubtedly outstanding."
  },
  {
    "original": "大学は、日本のトップの大学にするか海外の大学にするか、この頃から両親と話し始めた。母は日本の大学に進んでほしいようだけれど、父は海外大学を推していた。「私」は英語もできたので、選択肢はいくらでもある。\n\n父は、世界史のある分野で権威のある教授がいるという海外の有名大学がいいんじゃないかと言っていた。その教授とは知り合いで、たまにオンラインチャットで話すことがあるらしい。\n\n「彼にならお前を預けても安心できる」\n\n父が優しく笑いながら言った。\n\n私、本当は物理学を学びたい。その本心が言えたら、どんなによかっただろうか。\n\n「お父さんの知り合いなら、私も安心して留学できるよ」\n\n私はこう言うしかないのだ。\n\n日記帳には、高校一年生のとき父にゴルフを教わったとの記述があった。だから、いつかは連れていかれるだろうと覚悟していた。このエピソードは、めずらしく「彼女」が失敗する話だ。どうもゴルフは苦手だったらしい。それなら思い切り失敗すればいいと、舐なめてかかったのが私のミスだった。",
    "translation": "As for college, “diary me” had been torn between a top school in Japan and one abroad and had eventually begun discussing it with “her” parents. My mother, it appeared, had hoped I would choose a school in Japan, but my father suggested I go to a school abroad.\n\nAs for me, English was now no problem at all, so I had many options.\n\nMy father had a friend who was a preeminent scholar of world history who was working at a famous college abroad and he said that I should go there.  This scholar was an old friend of his and they had apparently been chatting about my future off and on via email.\n\n“If you could do a homestay with his family, I would at least know you’re alright.”\n\nHe had said, laughing kindly.\n\nFor me, I would rather study physics, and if I had been able to say that truth in that moment, I would have felt so happy.\n\n“Yeah… if it’s a family we know that would definitely be less stressful.”\n\nThis was the line I had gone with.\n\nIn the diary, there was a brief account where “her” dad had taught her golf when she was a sophomore in high school. For this reason, I had prepared mentally to be taken on this errand. In this episode: “she” had uncharacteristically not been up to the task. Apparently, she hadn’t been “…a huge fan of golf at all.” Unfortunately, this fact had led me to slack off on this assignment as all could think was, if that’s the case ill just suck on purpose and it will be fine."
  },
  {
    "original": "父に連れていかれた打ちっぱなしで、フォームや打ち方を教えてもらい、初めてのひと振り。父が見ているし、素人しろうとの振り方でそんなに飛ばないだろうと適当に打ったつもりだった。\n\nそれが、まっすぐ正面のネットまで一直線。私はしまったと思って父の顔を見た。案あんの定じょう、呆ぼう然ぜんとしている。たまたまだからと必死に言い訳をして、それからはわざと外して打つようにした。\n\n「彼女」に追いつかなくてはいけないし、「彼女」を追い越してもいけない。この絶妙なバランスの上で、私は生きている。\n\n日記を読み込んでおいて本当によかったと思ったのが、十七歳の誕生日パーティだった。友達を十人も呼んでのホームパーティ。あらかじめ人間関係を整えておかないと、こんな人数は呼べない。無差別に招待状を送ればいくらでも人は来るだろうが、それでは意味がないのだ。仲が良い十人。それが重要。\n\n高校に入ってからなんとか勉強の隙すき間ま時間を捻ねん出しゅつし、友達との時間を作った。一緒に買い物に行ったり、映画を見たり、カフェでおしゃべりしたり。「彼女」に擬ぎ態たいするためとはいえ、家族から解き放たれるこの時は私にとってかけがえのない時間ではあった。ただ、ホームパーティで親に何を言われるかわからないので、表面上は「彼女」らしい態度は崩さなかった。",
    "translation": "So, when my dad had brought me to the driving range, and had me instructed in how to hit and stand and so forth, and then watched as I hit my first ball- while he looked on, I had the thought …as a beginner, for sure, this ball isn’t going to go anywhere… I struck that ball with a random careless flick.\n\nOne random flick and it had flown out deep and directly into the safety net at the back of the range in one straight line. I thought …shit, as I looked toward my dad. And as expected, he was staring at me dumbfoundedly. It was just a fluke, I protested, and from then on, I changed my strategy to purposefully mishitting the ball for the rest of the session.\n\nI could never allow myself to fall short of “her” and, just as importantly, I could never allow myself to surpass “her.”\n\nI have spent my whole life on this sword’s edge.\n\nThere were times when I felt legitimately glad that I had dedicated so much energy to reading through the diary.\n\nFor example, my 17th birthday party.\n\nA party where she had invited “ten close friends over to our house.” To be able to invite this number of friends, it was key that I put time and effort into building and maintaining many human relationships.\n\nI could have just sent out scores of random invitations and I’m sure people would have come, but this would have defeated the purpose.  “Invited ten close friends over for a party.” “Close friends.” This was the key."
  },
  {
    "original": "友達への誕生日プレゼントは欠かさない。クリスマスにはちょっとした贈り物。バレンタインデーには可愛かわいらしい友チョコ。彼氏との悩みを聞いたり、勉強を教えたり、友達の友達を誘ってカラオケに行ったり。とにかく人との交流を増やすのに必死だった。\n\nそして、誕生日当日。集まった友達はちょうど十人。過不足なく彼女と同じ。\n\n飾り付けたリビングでパーティをしながら、みんなが私を祝ってくれる。プレゼントもたくさんもらった。\n\nでも今日は私の誕生日ではない。「彼女」の誕生日だ。それも、最後の。\n\nつつがなくパーティは終わり、私は疲れてため息をついた。\n\nこれが、十七歳の誕生日の出来事だった。\n\nこうして、危ういながらもなんとか彼女のレールを辿たどり、今まで過ごしてきた。",
    "translation": "After entering high school, whenever there was extra time in my schedule, I would eke out as much time as possible to hang out with friends.\n\nGoing shopping together, watching movies, chatting away in cafes – in a sense it was all an attempt to mimic “her” but more so I was striving towards a time when I would one day be free. The hard part was that for fears of what my parents might say when they saw my close friends, I had to maintain as perfect a surface level resemblance to her as possible -without ever breaking character.\n\nI spent years sending presents to friends on their birthdays. Small, thoughtful gifts for them at Christmas. Friendly chocolates on Valentine’s Day. I listened to their boy troubles, tutored them, invited friends of friends to go out to sing karaoke. Suffice it say, I invested a lot of energy into human communication.\n\nThen, on the big day. I had collected precisely the ten people required.\n\n“Her” to the t.\n\nEveryone celebrated with me in the midst of our decorated living room. And I got a lot of presents, too.\n\nBut it wasn’t even my birthday. It was “hers”. And it had been “her” last one too."
  },
  {
    "original": "しかしそれも、今日まで。彼女は死に、そして私が生まれる。\n\n初めて迎える誕生日のディナーは、言葉で言い表せないほど美味おいしかった。両親は、じっくりと料理を味わう私を見ながら、嬉しそうにワインを楽しんでいた。私と両親、それぞれ違う喜びを嚙かみ締めながら、フレンチのコースは進んでいった。\n\n「食後のお飲み物はいかがなされますか？」\n\n食べ終わった後、テーブル付きのウエイターが聞きにくる。父はいつものように答えた。\n\n「コーヒーを」\n\n全員分。そう続けようとした父の言葉を遮さえぎり、私は言った。\n\n「ひとつ、紅茶にしてください」\n\n両親が私を見る。ひどく驚いた顔をしていた。それがどういう意味なのか、私には想像することしかできない。娘がおかしくなったと思ったのか、それとも単に好みが変わったことにびっくりしただけなのか。ウエイターは御お辞じ儀ぎをして去っていった。両親は何も言わずに私を見ていた。そんな両親を、私は笑顔で見返した。いつもの人懐っこい笑顔とは違う、私自身の少し冷たい笑み。",
    "translation": "The party ran from start to finish without a hitch. And when “my” friends were out the door, I breathed one exhausted sigh.\n\nThis was the main achievement of my 17th birthday.\n\nIn this way, I have followed the rail of her life’s trajectory until where we found ourselves today.\n\nIn fact, I’ve ridden this rail to this very dinner table. Until today.\n\nToday, she’ will die and I will be born.\n\nAnd I can’t possibly express how delicious my first birthday dinner turned out to be. My parents looked on as I savored each course- with them sipping their wines with cathartic contentedness. My parents and I, both processing our separate triumphs as the French courses continued onward.\n\n“Shall I prepare after-dinner drinks for the table, sir?”\n\nSaid our tables dedicated waiter after the main courses were done.\n\nFather gave his usual answer.\n\n“Coffee please, for- “\n\n-All of us. He was about to finish, but I cut across him with.\n\n“-Could you add one black tea to that please, sir?”\n\nMy parents looked at me. Not trying to hide their surprise.\n\nAs for what would make them react to such a small detail, I’m afraid I can only guess. Perhaps they thought, oh our daughter has gone mad…” Or maybe they just were alarmed at my sudden change in tastes.\n\nThe waiter bowed and left the table.\n\nMy parents looked at me without saying anything, and I smiled back at them as they did. Not the usual, scripted and well-bred smile. But my own slightly cold and leering one."
  },
  {
    "original": "今日から先が、やっと私の人生。ハイヒールではなくスニーカーを履はき、スモーキーピンクではなくブラックのコートを着る。世界史ではなく物理を学び、そしてコーヒーではなく紅茶を飲む。\n\n人のクローン技術が汎はん用よう化されて、今年で二十年になった。今や人のクローンは一般に普及し、自らの遺伝子情報を保存しておく人がほとんどだ。\n\nＤＮＡの端についた、寿じゅ命みょうを決定付ける遺伝子を安全に操作する方法も確立された。ともすれば癌がんの原因になるそれは、人の手で無限に伸ばすことはできなかったけれど、消費された分を安全にもとの長さへ戻すことは十分に可能だった。これで、「ＤＮＡを保存した時点の年齢分、クローンの寿命は短くなる」という宿命から人類は、いやクローンは解き放たれたのだ。\n\nあと十年もすれば、記憶すら保存し復元できるようになるという。その保存は資金力のある富裕層から広まっていくだろうが、この両親は記憶の保存を望むだろうか。娘を失い、そしてまた得た。しかしそれは虚構だったのだ。そう遠くないうちに、彼らは十七年と３６４日の努力が無駄だったと知るだろう。あるいは、十七年と３６４日だけ夢を見られたことに感謝するだろうか。",
    "translation": "From this day forward, this was going to be my life.\n\nSneakers not heels, black coats as opposed to smokey pink ones. Physics not World History and instead of coffee... I. Will. Drink. Black. Tea.\n\nThis year will mark the twentieth one since human cloning had become standard practice. Now the act of cloning had reached the level of standardized popularity, and everyone – for the most part- had willfully gone ahead and saved their own genetic information.\n\nAs for the limits of DNA, the ones that determine life span- these had become easily manipulated through standardized means. By their own hand, humans couldn’t forever extend their own life span – at the end of which cancer tends to occur- but it had become easily possible to restore(return) the span to its original length safely. And thus, the problem of the “clones life starting from the age at which the genes were saved was no longer a burden on the fate of humanity-or clones rather.\n\nThere were also recent findings which seemed to indicate that, after another ten years, a person’s memories would also become bankable. That development would certainly spread among the wealthy who have capital to spend. But would these parents of mine want to have their late daughters’ memories saved?"
  },
  {
    "original": "それとも、もしかしたら。ほんの僅わずかな希望が頭を掠かすめる。\n\nお父さんとお母さんは、新しく生まれたこの私を、愛してくれるだろうか？\n\nあまりに儚はかない望みは、培ばい養よう器きの中で再生された私の脳内で霞かすみのように漂い、忘れることはあってもついぞ消えることはなかった。\n\n運ばれてきた紅茶を飲み、その香りに満足しながら私は喫きっ茶さ店てんで読んだ新聞を思い出した。コーヒーに手を付けず戸惑ったままの二人を置いてけぼりにして、絶妙にベルガモットが香る上質なアールグレイを味わう。\n\nもう少しして両親がこの世からいなくなったら、私も新聞の読者投稿欄らんに投稿してみようか。\n\n「我が家のクローン事情」って。\n\n【おわり】",
    "translation": "They had lost one daughter, and got another…\n\nBut that whole process had been nothing but fiction.\n\nSomeday, not too long from now, they would have to admit that they spent 17 years and 364 days for nothing. Or maybe they would be thankful for the 17 year long dream they had been shown?\n\nOr maybe, just maybe. And it was just a thimble of a hope that had crossed my mind on occasion.\n\nMaybe, this mother and father of mine would come to love this new version of me.\n\nThis fragile hope of a hope flits around in this brain of mine, a phantom in the mind of a clone who was raised in a test tube. A hope sometimes forgotten but never quite forgone entirely.\n\nAs I drank the black tea which had been brought over- contented by its pleasant fragrance- I thought about the newspaper article I had read earlier at the café.\n\nI shifted my focus away from the couple who, faces full of trepidation, still had yet to touch their coffee, and returned my attention to the taste of this exquisite Earl Grey- notes of Bergamot*(Italian citrus) rising above it in a delightful mist.\n\nI think I will just bide my time and wait for these parents of mine to pass away. Then, I think I will submit a reader response to that newspaper.\n\nIt will be titled, “Clones and their impact on our household.”\n\n(The end)"
  },

];

export const jordanFoolsBusPairs: SentencePair[] = [
  {
    "original": "「またこの人か」と思って、私はおばさんを見上げた。\n\n次のバス停で降りるために、私は座ったまま手を伸ばして、降車ボタンに触れる。車内には音が響き、全てのボタンが一斉に灯る。怪物の、の赤く光る眼のようである。\n\nバスが停車し私が立ち上がると、前に立つおばさんは、すかさず差し込むように体をじり、私の残した空席に腰かけた。バスは私だけを降ろして、次のバス停へと向かう。私は職場へ向かって歩き出す。このおばさんは、毎朝の黒い染みのようなだった。\n\n別にどうということは無いはずだった。おばさんは、私が毎朝ぴったりこの時間のバスに乗り、このバス停で降りるということを知っていて、毎朝私の面前に立っているというだけである。見たところ年齢は五十代かそれくらい。社会的な規範からいっても、まだ席をる必要性もないだろうから、私にはなにも不都合が無い。ただ、毎朝私の残した席に座られるだけ。しかし、私はそれが気に入らなかった。\n\nこのバスは、Ａ駅からＢ駅の間を運行している。私はＡ駅の始発で乗り込み、おばさんはその途中駅から乗り込んでくる。Ｂ駅はこの辺りでも一番大きな駅で、皆ここを目指しているのだから、私のように途中下車をする人などは居ないに等しかった。それなりに混みあう車内で、おばさんにとって私は都合の良い存在である。",
    "translation": "“Not this lady again…” I thought as I looked up at the woman.\n\nI was planning to get off at the next stop, so I raised my hand pressing in the drop off button. A sound echoed throughout the bus as all the drop-off lights lit up. Like the red glow of a many eyed monster.\n\nAfter the bus stopped and I stood up, without hesitation the woman twisted her body forward, inserting herself into the newly vacant seat.\n\nI was the sole passenger to disembark, and the bus then drove off to its next stop.\n\nI then started to walk to my place of work.\n\nThis lady was like a black and depressing stain on my daily mornings.\n\nAnd maybe there wasn’t even a substantial reason for me to feel that way. It was merely the fact that at this time every morning. In that seat. On that bus. I would eventually get up to leave – leaving it open for her at this stop. It was just the fact that she knew it and would stand over me waiting every morning. That’s what got to me the most.\n\nShe looked like she was probably in her fifties. She was therefore still outside the age range in which some societal rule would encourage me to yield up my seat to her. I was perfectly within my rights to stay seated. She was merely sitting down in the seat I would eventually leave every morning. But this was exactly what I hated most."
  },
  {
    "original": "だが、席を狙うおばさんののない眼つき、私の前の位置を人を押しのけてでも死守しようとするしさ、あるいはバスの中でのほんの数十分を「何としてでも座りたい」がために、こんなめなことをする彼女の、肉体のしさを私は憎んでいた。他の人は構わない。ただ、このおばさんにだけは、私のあとに座ってほしくなかった。誰かが、おばさんが乗り込むより手前のバス停で、私の前に立ったとき、私は心の中で応援した。どうか、おばさんよりも先にあなたが座ってくれますように。私の空席は、なにも知らない誰かに偶々訪れる幸運でなければならなかった。おばさんの座るそのときのために席を温める、予定された役割ではなく。",
    "translation": "This bus operates between stations A and B.\n\nI always take the first bus from station A, and the lady would get on a few stops down the line. Station B is the largest station in this area, and many people make their way there each day. So, it wasn’t an exaggeration to say that I was the only one on the bus who had to get off midway. And as it was often a crowded bus, my existence seemed to be particularly convenient for this lady.\n\nI just couldn’t stand her eagle-like-eyes, the lack of dignity with which she protected the space in front of me almost to the death, and just the bodily desperation of this miserable endeavor of hers – the desperate drive to be able to sit down for at least a mere 10-20 minutes. I hated the body that did this -her old run-down dumpy body is what I hated.\n\nI don’t care who, but if it was anybody but this lady sitting in my seat, I would be fine with it. And if someone was standing in front of me on that bus before she got on, I would always be secretly rooting for them from the depths of my heart. Please may you sit down in this seat before that lady gets a chance to! My empty seat was destined to go to some unknown person by pure happenstance. Not to become some pre-determined freshly warmed seat for this woman to sit in.\n\nToday, another woman in a suit had been standing in front of me. She was probably around 30."
  },
  {
    "original": "その日、私の前に立ったのはスーツ姿の女性だった。年齢は三十代といったところか。つり革につかまって、雑居ビルの看板だの、街路樹だの、やたらに車間の狭い対向車だの、目まぐるしく変わる窓の外を見ている。丁度よかった。おばさんと席を争ってもらうのに丁度いい。\n\n例えばこれが男性であると、男性のほうからおのずとおばさんに席を譲ってしまうというのが今までの経験だった。一応のレディーファーストの精神か、または、ただ単におばさんの情熱を帯びた無言の圧力に屈しているだけかもしれなかった。おばさんに勝つためには「座りたい」という信念がなくてはならない。そもそも体力のある男性は、Ｂ駅までの数十分、立って過ごしても構わない人が大半のようである。少なくともこのおばさんの代わりに座った場面を、私は見たことがない。\n\nでは、この女性はどうか。スーツを着ているということは通勤だ。足元は７センチのヒール。この後仕事を控えている。朝からなんて、なるべく疲れたくはないだろうから、目の前の席がけば迷わず座るだろう。もしかしたらいいものが見られるかも知れない。そう思うと、私の頭にかかっていた、朝もやのような眠気が次第に晴れていくような心地がした。",
    "translation": "As she held the handle strap which hung from the ceiling, she glanced around at the rapidly changing scenery- at all the billboards for apartments buildings, at the trees lining the paved sidewalks, at the other cars zipping by the other way outside.\n\nThis was perfect.\n\nShe was the perfect candidate to make an attack on the lady’s seat.\n\nIf for example it had been a man of the same age, the man would probably just end up giving the seat to the lady anyway – or at least that had been my experience up until this point. The vague, “ladies first” mind set, or rather one that was simply a silent capitulation to the lady’s silent but fervent pressure.\n\nIn order to win against the lady, one truly needed to feel the urge- “I must sit”- with real conviction. And from the start, for the large portion of men who had a fair amount of stamina, it didn’t seem much of a hassle to stand on the bus for 10-20 minutes before they made it to station B.\n\nI hadn’t, up until this point at the very least, ever seen someone sit in my empty seat who was not the lady.\n\nBut how about this 30 something woman?\n\nIf she was wearing a suit she must have been going to work. Looking towards the floor I made out a pair of 3-inch heels. After this she has a job to do. And no one wants to tire themselves out first thing in the morning… so if a seat opens up before her very eyes, she’ll surely sit in it. I might be able to see something pretty great here. And as I thought this, I felt the morning cloud that had been fogging up my mind slowly give way to a feeling that could only be described as sunshine."
  },
  {
    "original": "少し経ってバスが停車した。のおばさんが乗り込んでくるのが見える。私は寝ているかようにきながら、さり気なく様子をう。\n\nまず、おばさんは運転手に定期券をちらつかせながら車内を見渡し、すぐに私の席に近づいた。次に、つり革をむと、スーツの女性の隣に差し迫り、半歩分の足を女性に向かって突き出した。\n\n私は横目で女性を見上げた。彼女は「意味が分からない」といったな表情を浮かべている。それもそうだった。何も事情を知らなければ奇妙に映ることだろう。車内に空いているつり革など他にもあるのだし、わざわざ彼女の隣を陣取るのは不可思議である。しかし女性は、持ち前の都会人らしいで、にじり寄るおばさんについて放念し、無視をきめることにしたようだった。",
    "translation": "After a short while, the bus stopped again.\n\nI saw the lady in question climb onboard.\n\nI had my head tilted down as if I was asleep and from this viewpoint, I could nonchalantly make out how she was reacting.\n\nShe started by scanning the inside of the bus as she fleetingly showed her bus card to the driver and then proceeded to make her way over to where I was sitting.\n\nNext, she grabbed the handle strap above and fell in line directly next to the woman in the suit, turning her right foot outward a half step in the younger lady’s direction.\n\nFrom the corner of my eye, I glanced up at the lady in the suit and saw the irksome pall which had fallen over her face which seemed to be saying …what is this woman’s deal?\n\nShe had a fair point. If there was no context at all, it would appear to be a mysterious situation to anyone. There were empty handle straps elsewhere on the bus, and her taking up a spot directly next to someone without an obvious need to, looked plain odd. But the suited lady, in an act of deft societal know-how, had seemingly decided to dismiss the lady sidling up on her- deciding rather to ignore her instead."
  },
  {
    "original": "そのまま数分バスに揺られている間にも、おばさんは隙を見せなかった。自分が不利になりそうな要素を徹底的に排除するのが、この間、おばさんのな務めであるかのように。\n\nいよいよだった。私が降車ボタンに指先で触れる。ランプは音を立てて光る。バスが次第に速度をめたとき、おばさんはど、横の女性にぶつかるようにして位置を取った。いつもなら、私が立ち上がればそのままおばさんが体を捻じ込み、なんてことない表情で座席に腰を下ろすことだろう。しかし今日であれば、あるいは。\n\nバスが停車した。ため息のような空気圧の音がして、扉がひらく。私は席を立ちあがる時、普段よりもゆっくりと、さらにおばさんに私のカバンを当てて進行の邪魔をするように、女性とおばさんの間を通り抜けた。私は降車のきわ、後ろ目で結果を追う。\n\n勝った。女性はヒールのを、おばさんよりもかに先に進め見事、座席に落ち着いたようである。音を立てて扉が閉まる。バスが遠ざかる。\n\nその日は一日、なんだか浮ついたような心地で過ごした。どうしようもない種類の喜びだった。",
    "translation": "In this way, several minutes passed as the bus shook and shimmied onward. During which, the older lady had continued to stand on the suited lady’s coat tails. It was as if her righteous mission was to eliminate any chance of being at a disadvantage to gain the seat.\n\nThis was the moment.\n\nI pressed the “please stop” button above me. The lamps around the bus were alight. The bus slowed down to a gradual stop.\n\nAt this moment, the lady had taken up a position that was almost on top of the suit lady next to her.\n\nIf things took their usual course, this was the point where the lady would twist her body past me into the seat when I stood- without a trace of emotion or recognition on her face. But today of all days, maybe not…\n\nThe bus stopped.\n\nA sound like sigh escaped the bus in a burst of hydraulic pressure as the bus door opened.\n\nWhen I went to stand up, I did so slower than usual- allowing my briefcase to dangle in the path that the oncoming lady always took. Interposing myself between the suited lady and her. And as I went to step off the bus, I gave a passing glance to see how my plan had gone."
  },
  {
    "original": "◆\n\n次の日は、最近では珍しい土砂降りで、車内はいつもより混雑していた。肌がべたべたする湿気、生乾きの服のい、傘からるに汚れた水。人の熱気と交わって、空気は重く蒸されている。\n\nバスが停車し、いつものようにおばさんが乗り込んできた。昨日のようにはいかないだろう。あんなに運の良い日はにない。今日はまたいつも通り、この席はおばさんに占拠される。\n\n私がうんざりして顔を上げた時だった。なんと、おばさんが二人に増えているではないか。私の見間違えだろうか。夢か、湿気の見せた幻か。しかしもう一度よく見ても、私の目の前には、やはりおばさんが二人並んで立っているのだった。\n\n思えば、今までおばさんの顔をまじまじと見たことはない。なんとなくの低めの背丈、白髪の混じる短い髪、つり革を摑むやせぎすの手首で、ああ、あのおばさんだと判断していた。\n\n私は、二人のおばさんをよく見比べた。よく見れば、当たり前だが違う顔だ。ただして同じ造形だった。私はもともと人の顔を覚えるのは遅い方だし、これでは区別がつかなくても仕方がない。そのまま、おばさんの持ち物に視線を滑らせる。一人は黒いリュックサック、もう一人は、赤いトートバッグを持っていた。",
    "translation": "Yes! And wouldn’t you know it!\n\nThe suited lady had beaten the lady to the seat by a heel’s toenail. She was seated- looking calm in victory.\n\nThere was another sound as the bus door closed behind me and it drove off into the distance.\n\nI spent the rest of that entire day floating. The type of happiness that presses itself upon the heart assertively but without apparent reason.\n\n*\n\nThe next day, we were hit with a deluge, the likes of which we hadn’t seen for quite some time. And as a result, the bus was packed a bit tighter than usual. There was a heat that made you sticky with sweat, a smell of half dry linen, and dusty water on the floor from the drip drop of wet umbrellas.\n\nThe mass of heated bodies was turning the air on the bus into a steam room.\n\nThe bus stopped, and the lady – as always- got on.\n\nI was sure it wouldn’t turn out like yesterday. Lucky days like that were a rarity. And yes, today, as always, the seat was eventually captured by the lady.\n\nBeside myself, I had lifted up my chin to look at her before standing up.\n\nAnd it was at this same moment that I noticed one lady had suddenly become two!\n\nCould it have been my eyes playing tricks on me? A dream? A phantom of the muggy rainy-day-bus-heat?\n\nI looked again and it was indeed the case – there were two ladies now standing abreast in front of me."
  },
  {
    "original": "私は、どちらのカバンにもよく見覚えがあった。ということはつまり、二人いたのだ。私の席を狙うよく似たおばさんが、二人。\n\n昨日、スーツの女性と席を争って座れなかったのは、黒いリュックのおばさんの方だ。人の顔の見分けがつかないので、私はよく持ち物で人を判断する。\n\nカバン、、時計など、服よりも変えるが低い小物、こっちのほうがその人を決定づける要素に富んでいた。かたや人間ときたら、大体似たような肌の色の上に、これまた似たようなパーツがついているだけで分かりにくい。人の顔も、もっとカバンのように赤や緑や紫色だったり、目鼻の数だって、配置だっていろんなパターンがあればいいのにと思う。その方が単純で分かりやすい。",
    "translation": "Now that I came to think of it, until now I had never seriously considered the lady’s facial features. She was a somewhat short woman, hair salt, and pepper, with boney wrists which held a strapped leather bag. These features were how I had always recognized her.\n\nI considered the two ladies and their faces more closely. On closure examination, yes, their faces were rather different.\n\nHowever, they were of a similar mold for the most part, and I thought it was no wonder why I had confused them.\n\nI slid my gaze down to what the ladies were carrying. One had a black backpack, the other a red leather tote bag.\n\nI recognized both objects as I had seen them swinging in front of my face on countless occasions.\n\nThis was how I discovered there were two. Two doppelganger ladies gunning for my seat.\n\nYesterday, the lady who had fought the suited lady and lost had been Black Bag.\n\nI guess I did this quite often…learning the difference between people not from their faces – which I’m dreadful at – but rather by what items they carried.\n\nShoes. Bags. Wristwatches. Items that people didn’t often swap out as they tended to do with various outfits – these were rich sources of material from which to recognize another person.\n\nPeople on the other hand, have around the same skin color, and similar parts- hands, ears, feet etc. Which makes them hard to distinguish from one another."
  },
  {
    "original": "私は、どちらのカバンにも席を取られたことがある。黒リュックにも、赤バッグにも。本当は『取られている』わけではないので、これは正しくない表現だが、心情としてはこちらのほうが近かった。\n\n黒おばさんと赤おばさんは、互いの足元をしあうように見つめている。おそらく私が気がつかなかっただけで、今までもこのような場面があったのだろう。蒸し暑い車内で、ここだけ細い糸のようなピンとした冷たさが張りつめていた。\n\n私は降車ボタンに触れた。音と共にランプが光る。私に視線がぐっと集まったのが分かった。見られている。私の足を、腰を上げるその瞬間を。\n\nバスが止まる。勢いが急だったため、私たちは少し前のめりになった。私はゆっくりと腰を上げて立ち上がる。おばさん二人は、私にぶつかるようにして、静かに席を取り合う。\n\nどちらも同じだった。黒でも、赤でも。私はどちらのおばさんも、同じだけ嫌いだった。だから、戦いに勝った黒おばさんが席に座ったところを見ても、どうでも良かった。",
    "translation": "If people’s faces had the variety of handbags- different numbers of ears and eyes, or varying patterns of arrangement, that would be great, I think. That would be a lot simpler and easier to keep up with.\n\nAs for my seat, it had been taken by both of the bags in the past. Black Bag and Red Bag.\n\nIt really wasn’t fair to use the word “taken” here I guess, but it would have to suffice as it was closest to my underlying feelings on the matter.\n\nToday, Black Bag and Red Bag were staring at each other’s feet as if to stave off the other.\n\nUntil now I must not have noticed, but a standoff like this must have occurred before now.\n\nThis standoff between them had created a small but rigid thread of cold loathing in the otherwise hot and steamy bus compartment.\n\nI pressed the drop-off button. And the lamps around the bus came alite in unison.\n\nI felt their concentration on me all of the sudden. I was being watched.\n\nThe moment when my foot and hips would slowly rise was being scrutinized.\n\nThe bus stopped- and had stopped with such force that we were thrown forward a bit in its inertia. I stood slowly, rising up out of the seat. The two ladies, bumping into one another, commenced their quiet struggle for the empty seat."
  },
  {
    "original": "ただ、変な争いに巻き込まれてしまったな、と思った。\n\n◆\n\n二人のおばさんについて見分けがつくようになってから（といっても相変わらず顔ではなくカバンの色だが）、毎回、二人同時に乗ってきているわけではないことを知った。\n\n多少の変動はあるが、月曜には黒おばさんだけが、そして金曜には赤おばさんしかいないのだ。その間の火・水・木には二人が乗っていることが多い。その場合も、横並びになることは、よほど車内が混みあっていない限り殆どなく、どちらかが私の前、もう一人はその対角で目を光らせている。\n\nと、こういった具合に。小規模な生態調査のようである。渡り鳥研究家が、ハクチョウがいつの季節にどこにいるのかを観測するように、私はいつのまにかおばさんたちの行動パターンを理解していた。\n\n特徴があるから、憶えやすい。彼女たちはいつも同じカバンを持って、同じバス停から乗り込んで、同じ席を取り合って……。ここまで思って私は「私もそうだからかも知れない」と初めて気がついた。私も、いつも同じカバンで同じような席にいるから、簡単に憶えられてしまったのだ。",
    "translation": "Both were the same. Black Bag, and Red Bag.\n\nAnd I hated them both. The same.\n\nAs was the case, when I saw that Black Bag had finally won the seat, and I saw her sitting down inside it, it was little if any consolation to me.\n\nI merely thought …wow what a weird battle I have been drawn into.\n\n*\n\nEver since I became able to tell the two apart (even if I was only doing so based on the color of their bags and not facial characteristics) I also became aware of the fact that they weren’t always riding the bus at the same time.\n\nBarring the odd out of place day, Monday was Black Bag, and Friday was only Red Bag. The days in between- Tuesday, Wednesday, and Thursday were often shared by both of them. And even then, while the chances of them standing next to one another on the busiest most crowded days were slim, for the majority of the time at least one of these two was standing over me with the other to the side, eyes flashing.\n\nTo my mind, I viewed my study of the bag ladies as a small scope ecological investigation. For example, the researchers of Watari Island know when and where swans will be based on the season. In this same way, I came to understand the movements of the bag ladies.\n\nThey are easy to remember because of their individual characteristics. Each woman carries a specific bag and gets on at a certain bus stop, and always vies for the same seat… And since I had thought about at some length, I had also started to realize that …maybe was the same way."
  },
  {
    "original": "一瞬でわかってしまうから、乗り込んだら即座に私の席の前に立つのだ。となれば、が効くかもしれない。私が私だと、おばさんたちにバレなければいい。\n\n私は、次の月曜日いつもとは違う色のカバンを持ち、を掛けた。座る場所も、出口から少し遠い奥まった場所に移動する。このカバンはひと回り小さく、いつもより荷物が入らなかったし、眼鏡のせいでいつも付けているコンタクトよりも視界はぼやけていて、おまけに出口から遠いとなると降車時には人をき分けなければならないという、これらすべての点で私に不都合だったが、これも、なにもかも、おばさんに席を取られないためなら、それでよかった。\n\nおばさんたちのためではなく、他の誰かに不意に訪れる幸福になりたい。純粋な願いだ。私はそのためにできる限りを尽くすのみである。\n\nしかし、私の見通しはどうやら甘かった。黒おばさんが乗り込んできたとき、おばさんは車内を見渡して、少しの間は私を見逃したものの、すぐに足はまっすぐこちらに向いた。顔を、憶えられている。この人は持ち物ではなく、私の顔を憶えている。私の、これといって特徴のない顔を。",
    "translation": "I, too, was always carrying the same bag and sitting here in the same seat. I had made it too simple for them to remember my patterns.\n\nFor them, as quickly as blinking, they would get on and then b-line it to the space in front of my seat. And if this was the case, maybe a disturbance to the system would work? If they couldn’t tell me for me, perhaps I could escape the lady’s detection.\n\nThe following Monday, I brought a different colored bag and wore glasses to work. I also changed the place where I was sitting, choosing instead a seat farther from the front, towards the back upper seats of the bus. This new bag was smaller and I couldn’t carry much. Also, compared to the contacts that I always wore, these glasses reduced the world around me to a slight blur. Not to mention, the seat I had chosen would now force me to shoulder my way through a mass of people as I exited the bus. All of these points weren’t exactly in my favor, but if all of this would prevent the ladies from getting my seat then it would all be worth it.\n\nBy yielding up my vacant seat, I wanted to become an unexpected source of happiness, not for these ladies, but for some other person. It was an innocent enough request. And I merely wanted to do everything in my power to make it a reality."
  },
  {
    "original": "行きずりの人を顔だけで判別できるなど特殊能力だ。きっと私は、おばさんがカバンを交換していたら、二人が入れ替わっていることなど気づけない。\n\nえ無く、私の空席はおばさんに明け渡された。もう諦めることしかできないのだろうか。ちで首元が熱く感じたそのとき、脳に住む、理性の双子が私にく。\n\n「私のあとの空席がどうなろうと、最初から気にする必要はないし、いちいちこんなことでストレスを感じることこそ損だ。非合理的だ。そんなことよりも、もっと建設的なことを考えましょう。毎日、晩御飯ので頭を悩ませているじゃない。こういうの時間を、に活用したらいいのに」\n\nそれもそうだ。自分がこんな損までして、人に嫌がらせをする必要なんてない。",
    "translation": "Alas, it appears I had overestimated my own ability to deceive the ladies. When Black Bag got on the bus and swept her gaze across its interior, even though she looked over me at first, she then turned her legs straight in my direction. She had remembered my face, it appeared. Not my possessions but my face. This… not-so-distinct face of mine.\n\nShe could actually tell the difference between people she met randomly out in public. What a skill! If it was me, and the ladies switched bags or even traded places entirely, I wouldn’t have the slightest clue.\n\nAnd sadly, my empty seat ended up being surrendered up to the lady yet again.\n\nWas there anything for me to do but to just give up? I felt the frustration as a heat budding up from the back of my neck, but then I heard a voice, perhaps a whisper from the wiser side of my mind.\n\n“Regardless of who gets your seat after you leave it, from the beginning there is no reason to care about it at all, and besides, allowing stress in from all these niggling annoyances is a waste of energy. It is irrational. Instead of this business with the ladies, let’s think of something more constructive. You don’t get bent out of shape by the details required to arrange dinner every day, do you? It will all be better if you just use this small time on the bus for something more productive!”"
  },
  {
    "original": "私は次の日から、強い意識が必要だったが、なんとかおばさんたちのことを気にしないよう努めた。始めは、その見知った姿格好が視界の端に入るだけでも不快だったが、窓の外の歩行者や、時折散歩で通りかかる犬の姿を見て、気をらわせる日々を重ねていくうち、次第におばさんのことがどうでもよくなってきた。\n\nおばさんたちはその間も相変わらず、惑星の運行のように定められて私の前まで来た。二人並んだ時も、私はどちらの敵にも、味方にもならないように振る舞った。これは占いだ。黒と赤、どちらが勝つか、その日の運勢を適当にけてみる。\n\nもし黒が勝ったら嫌いなあの人から電話がかかってこない、赤が勝ったら、かかってくる。黒が勝ったら帰りに雨が降る、赤だと晴れる。こんなように。\n\nに関しては、の亀裂と同等だったが、この新しい試みはなかなか私を楽しませた。これだ、と思った。自分の中の悪意との正しい付き合い方。しかし、それにもやがてきた。\n\n◆\n\nその日の黒おばさんは、いつもと少し様子が違った。月曜日のことである。赤は月曜日には現れないので、今日は黒一人だけだった。",
    "translation": "That was the truth. Allowing myself to waste so much time and energy, allowing them to get under my nerves in this way. It was all unnecessary.\n\nEven though it took a considerable amount of willpower, I got on the bus with the mission of not paying the ladies any undue attention.\n\nAt first, just having the form of their silhouette slide into my peripheral vision was hard to tolerate, but after days of continuous effort I was able to slowly distract myself with other things; the people walking on the sidewalk, seeing the dogs out on their routine walks as they strolled along- gradually the idea of the ladies seemed to not be such a big deal.\n\nDuring this time, the ladies behaved in exactly the same way, like the steady drift of some celestial object in orbit they would take their spot in front of me. And when they were aligned next to one another, I would behave as if I didn’t favor one or the other. This was just some kind of horoscope. Black or Red, whoever was the winner, would determine whether I would have a lucky day or not."
  },
  {
    "original": "黒おばさんはなにやら、そわそわと私の頭の上のほうを眺めたかと思えば、窓の外に目線を移したり、カバンに何度か手をやってやめたり、要するに不審だった。\n\n私はぼんやりと眠るようにして、気取られないようにおばさんの様子を観察していたが、ふいに私の手になにかが触れた。薄くて硬くて、チクチク痛い。驚いて目を開くと、おばさんは私になにかを差し出していた。それは小さなお菓子のようだった。中身は見えない。文字の印字されていない、小さな銀色の包装に包まれている。そのギザギザの袋のじ口が、私の指の側面をめ、刺激を与えていたのだ。\n\nおばさんはなに私と目を合わせようとはしなかった、無言で、このチンケなを差し出している。\n\n私は失望した。賄賂がこんな得体の知れないお菓子だったからではない。おばさんが賄賂をなんてものを差し出したこと自体に、私はしていた。彼女はもっとしいのではなかっただろうか？　おばさんはきっと私に自分が認知されていることを分かっている。分かったうえで、毎度私の席の前を確保し、人を押しのけ、多少無理があっても強引に座る。それは、私にどう思われてもいいからではなかったのか。",
    "translation": "If Black won, I wouldn’t end up getting a call from that person I hate, if Red won, the call would come. If Black won, it would rain on my way home tonight, if red won it would be sunny. This was how I spent my time.\n\nIn terms of the dependability of this system, it was about as reliable as reading the branching cracks on a turtle shell, but even so, this new game of mine had become quite fun.\n\nThis was it, I thought.\n\nThis was a much better way to relate to my baser urges.\n\nHowever, this game too, soon was also not enough to fix the situation.\n\n*\n\nOne day, Black Bag was different than usual. It was a Monday. Black Bag was alone as this was Red Bag’s day off.\n\nBlack Bag, for some reason, was shifting between looking at the space above my head and restlessly shifting her gaze to the world outside the window- trailing her hand down to her bag in tentative and repeating cycles. In short, all abnormal behaviors.\n\nGiving off the air of someone asleep, I had been observing black bags actions so that she wouldn’t notice, but before I knew it, something was touching my hand. It was thin and hard, and painfully crinkly.\n\nIn surprise I opened my eyes. The lady was extending something out to me. It appeared to be some type of hard candy. I couldn’t quite see what was inside of it as it was wrapped in a small silver package which had no lettering on it."
  },
  {
    "original": "私にとって彼女は、押し迫る壁のようなもの、または災害などのような、人間性の外にあるものだった。災害は、交渉などしい人間のなどするべきではない。柔らかく腐ったりをするべきではない。人間じゃなかったから、私は今まで彼女をなんとか許すことができていたのに。このとき私は、初めて心の底から彼女を呪った。\n\nだからといって、突き返すのも違う気がした。私は、差し出され続けるお菓子の包装紙を見る。私はおばさんに対して、それを受けとる、拒否するという能動的態度を示したくなかった。私はおばさんの差し出すものをそのまま無視した。降車ボタンに触れる、バスを降りる。残された座席はそのままおばさんに渡った。",
    "translation": "The sharp edge of the packaging had been grazing the side of my finger, which is what had gotten my attention in the first place.\n\nThe lady was obstinately refusing to meet my gaze. Mutely, she was offering up this pitiful little bribe.\n\nI was so disappointed.\n\nNot because the bribe was some non-descript hard candy, I was discouraged that she would stoop to bribery at all.\n\nWasn’t she supposed to be a cunning schemer? The lady must have noticed that I had noticed her. And regardless, she had continued to vie for the space in front of me, pushing others aside, going out of her way entirely at times to jam herself into my seat. Did this not show how much she didn’t care about what I thought of it all?\n\nTo me this woman had seemed like a wall that closes in on you, like a natural disaster of sorts- something completely outside of human control. Disasters are not something we should lavish with cheap negotiations. They should not be met with soft and rotten placations. She hadn’t been human before, and for that very reason, I had been able to forgive her actions until now. This was the first time I felt a legitimate curse for this woman deep down in my heart.\n\nHaving said that, slapping the thing away outright seemed like the wrong call."
  },
  {
    "original": "翌日火曜日、黒おばさんはまた私に賄賂を差し出した。りない。私は昨日のようにまた無視しようとしたそのとき、私は黒おばさんの背後に赤おばさんがいることに気がついた。\n\n赤は黒おばさんと背中合わせになるようにして立っているが、顔はしきりに私の座席をっていた。そのとき、私はふと思いついた。手元に押し付けられるお菓子の包装を見る。これを、受け取ってみたらどうなるだろうか。\n\n私は指にチクチク触るそれを、手の中に納めた。黒おばさんは相変わらず無言のまま、持つべきものが無くなった自分の手を引きあげる。私はそのとき、チラと赤の様子を観察していた。赤は間違いなくその瞬間を見ていた。\n\n私しか降りないバス停の名が車内放送で示されたので、私はボタンに手を掛ける。そして降車のきわ、黒に向かって、しかしむしろその言葉を赤おばさんに聞かせるようにして、「どうぞ」と言って席を立った。その時、黒は私を見た。一瞬、私たちの視線は交わって、しかし間もなく離れる。私はバスを降りた。明日、どうなるかが少しだけ楽しみだった。",
    "translation": "I looked down at the candy that was still being extended in my direction. Trying not to show the lady that I was denying it outright or accepting it freely. I looked at the item being extended my way and ignored it.\n\nI pushed the drop-off button and got off the bus. The seat I had left empty was thus left to the lady.\n\nThe next day -Tuesday. Black Bag extended yet another bribe my way. She clearly hadn’t learned her lesson.\n\nWhen I went to ignore it like the day before, I noticed Red Bag standing behind her.\n\nRed was standing right next to her, their shoulders abreast, but red was clearly looking over at my seat. Just then, I had a new idea. I looked down at the hand which was offering the hard candy. What if I took her up on her offer?\n\nI took the scratchy thing up in my hand.\n\nBlack Bag went to withdraw her hand silently. And just at that moment I looked over at Red Bag. Without a doubt she had seen the exchange.\n\nThe bus station where only I got off’s name was announced over the loudspeaker. I extended my hand up and pressed the drop-off button. And when I went to stand up, I turned to Black Bag and said, “there you go, mam!”\n\nFor a second we exchanged a glance, and then it was over as we both looked away. I got off the bus.\n\nI wonder how things will turn out tomorrow… I thought- relishing this new development."
  },
  {
    "original": "◆\n\n次の日の水曜も、黒おばさんは同様のお菓子を差し出してきた。私は、の知らない人からったものなど当然食べる気はないので、昨日の賄賂はそのままゴミ箱に捨てていたが、しかしそんなこととは関係なしに、今日も私はその指に触れるものを手の内に納めた。\n\n赤おばさんは、昨日と同じような位置からやはりこちらを見ている。敢えて、例えばもっとお菓子を見えやすいように受け取ったりして、アピールをするようなことはしない。不自然だし、なにより赤おばさんはどんなな動作でも見逃さないだろうという嫌な確信があったからである。\n\n私は、また黒に「どうぞ」と言って席を明け渡した。黒は何もいうことは無く、しかしいつもより余裕のある動作でそこに座る。赤はその間、少しも動かなかった。しかし、目だけはしっかりと黒おばさんに向けられている。私はそのままバスを降りた。\n\n次の木曜日、やはり同じようなやり取りがあり、席は黒にられた。私は、もしかしたら見当はずれだったかもしれないと思った。赤は以前として動かない。この日も席は、黒おばさんが座った。",
    "translation": "*\n\nOn the following Wednesday, Black Bag offered up the same hard candy. As I wasn’t about to eat something I received from a stranger, of course I had thrown yesterday’s bribe into the trash, but that wasn’t exactly the point, and today as well I accepted the scratchy thing into the palm of my hand.\n\nJust as she had been the previous day, Red Bag was looking on from the side.\n\nI tried my best not to make the gesture of taking the candy from Black Bag too pronounced. As I was oddly certain that Red Bag would be able to tell if even the slightest movement of mine was unnatural.\n\nAgain, I stood saying, “There you go, mam” to Black Bag- passing over my open seat.\n\nShe didn’t make a reply but took the seat with much more grace than always.\n\nRed Bag didn’t move as this played out. But she did have her gaze firmly trained on Black Bag.\n\nAnd at that I got off the bus as usual.\n\nOn the following Thursday, the same charade was played out, and I yielded up my seat to Black Bag.\n\nI was starting to think I may have misjudged the situation.\n\nJust as before, Red Bag didn’t make any attempt to move towards the seat. And just as the two days prior, the seat went to Black Bag.\n\nHowever, the next day – a Friday- was a day when Black Bag would not be riding. And as Red Bag came up to stand in front of me, she reached out to hand me something as if she had previously planned to do so."
  },
  {
    "original": "しかし、次の日の金曜日。黒が乗ってくることのない日。赤は私の前まで来ると、思い切ったようになにか差し出した。\n\nやっと来た、と思った。私はこの時を待っていたのだ。\n\n赤おばさんは黒と違って、真っすぐに私の目を見ていた。私はそこで初めてまともに正面から、赤おばさんの顔を見た。これといった特徴のない顔だ。それでもよく見て、何かをそうとすれば、顔のほくろが他の人よりも多少多いかも知れなかった。それも、ほくろなのか顔の染みなのか、老いによって少しずつその境界は崩れ始めている。目元には初老のが刻まれている。皺の間にはよれたファンデーションがわだかまっている。敢えて挙げられるのはこれくらいだった。\n\n私が顔をじっと見すぎていたのか、おばさんは顔でも私に手元を見るように示した。手をずいと近づけて、顔をめる。私は従って、目線を手元に下ろした。",
    "translation": "Finally! I thought. I had waited for this very moment.\n\nIn contrast to Black Bag, Red Bag looked me directly in the eye.\n\nThat was the first time I had seen her from the front, in full view. Even so, it was an unremarkable face. If I tried to find something to relate, perhaps she had more moles on her face than the average person, I wasn’t sure if they were moles or liver spots actually- maybe her age had slowly started eating away at the boundary between the two. Smile wrinkles were carved around her aging eyes. The foundation she had applied took up the spaces between them. This seemed to be the best she could do.\n\nPerhaps I had been looking at her face for too long, because after a while Red Bag gestured with her chin for me to look down.\n\nI promptly brought my hand up, dipping my chin to inspect the thing.\n\nRed Bag’s bribe was a paper.\n\nIt looked around the size of a business card. I took it up in my hands and proceeded to check what was written on it. From the amount of information that was scrawled across it I knew instantly that it was not in fact a business card. Thank God it wasn’t a business card!\n\nIn the midst of this cheap squabble over seats, the person who proudly touted their full name and place of work could be none other than an indomitable beast, against which I-nor anyone- would have any chance of victory."
  },
  {
    "original": "赤おばさんの賄賂は紙だった。名刺くらいのサイズの小さな紙。私はとりあえず受け取って何が書いているのか確認する。パッと見の情報量の多さから、名刺でないことは明らかだった。名刺じゃなくて良かった。こんなにケチく人と席を取り合っているような人間が、堂々と所属と本名を明かしても構わないのであれば、この尊大な怪物に勝てるものなどいないのである。\n\nともかく、私はその紙を見た。コンビニの引換券のようだった。対象商品を規定の数買うと、後日ペットボトルのお茶や、カップラーメンなどと引き換えられるといったキャンペーンの紙が貰えることがある。おばさんが渡しているのはその種類だった。\n\n財布にゴチャゴチャと挟めていたのか、赤おばさんの顔同様、いくつも薄い皺がついている。引き換え対象商品、ペットボトルの水。期間は今日から翌週の終わりまで。私は受け取った紙をカバンの中に仕舞った。\n\n黒おばさんから貰う、食べられない菓子よりはよっぽど有用な賄賂だった。私は仕事帰りにコンビニに寄って、貰った水をなんとなしに飲みながら、次に二人が乗ってきたら、今度は赤おばさんに「どうぞ」と声を掛けようかと考えた。",
    "translation": "Regardless, I continued to scan the paper.\n\nIt appeared to be a coupon for a convenient store. If you bought a certain number of certain products, you would receive things like bottled tea or cup ramen when you exchanged the coupon during a subsequent purchase. The paper was a coupon for one free water. This is what Red Bag had chosen to pass my way.\n\nPerhaps it had been enclosed in her wallet, because like her face, it too had several thin wrinkles across its surface. The expiration date of the ticket was sometime early next week. I put the paper away in my bag.\n\nThis coupon was slightly more useful than the candy I would never eat from Black Bag. And as I drank the bottle of water I had gotten from the convenience store on my way home, I thought to myself. Next time I will be saying, “Please sit here, miss” to Red Bag instead.\n\n*\n\nThe next time they both were both assembled in front of me on the bus was the following Tuesday.\n\nOn days when Red Bag was missing, Black Bag had seemingly decided – in her miserly fashion – that a bribe was not required to gain a seat that was not contested. So yesterday she hadn’t extended that dubious hard candy to me at all. This wasn’t altogether a big deal to me, but this alongside her general air of poverty made me hate her all the more."
  },
  {
    "original": "◆\n\n二人が揃ったタイミングは、次の週の火曜日だった。\n\n黒おばさんはその吝嗇さ故に、赤おばさんのいない、つまり確定で座ることのできる日には賄賂は必要ないと判断したようだ。昨日の月曜日、黒おばさんは一人で乗ってきたため、私にあの不気味なお菓子を渡してこなかった。一向に構わないが、彼女のこんな貧しい現金さも併せて嫌悪の対象だった。\n\nしかし今日は、黒おばさんの隣に、赤おばさんが迫っている。黒は赤おばさんの存在を認識してから、いつものように私にお菓子を差し出した。私はそれをすぐには取らず、黒おばさんにもハッキリ分かるように、隣に並ぶ赤おばさんをぎ見る。\n\n赤おばさんは黒をし、財布の中からなにやら取り出して、私に向けた。今度も名刺ほどの紙だった。ハンバーガー割引券。よくもまあ、こんなものを取っておけるものだ。私であれば、貰ったその日に失くしてしまうだろう。",
    "translation": "But today, Red Bag was in her usual place next to Black bag. Once Black Bag seemed to notice Red Bag’s presence, she proceeded to hand me the usual candy. But I did not take it right away, instead I looked up at Red Bag who was standing beside her.\n\nAfter glancing over at Black Bag, Red Bag pulled something out of her wallet and went to hand it over to me. This time too, it was another business card sized paper. It was a coupon for a free hamburger at the convenience store.\n\nI am baffled that people take the time to save little papers like these. If it was me, I’d certainly lose it immediately after receiving it.\n\nI considered this bounty I had received from both Red and Black, and ended up taking the hamburger coupon.\n\nIt wasn’t that I had liked the coupon, I had no plans of buying a hamburger nor did I even like them. No. My only goal had been to get Black Bag to discover Red Bag’s bribe. If this happened, Black Bag would come to the table with a new bribe- without a doubt. And this became my new game with the two ladies.\n\nEarly the next day, Black Bag passed me a 3-dollar coupon that I could redeem at the local outlet mall. And Red Bag had her usual convenient store coupon."
  },
  {
    "original": "私は黒と赤の贈与品を見比べ、ハンバーガーの割引券を選んで取った。ハンバーガーを買うような予定はないし、別に好きでもないので割引券にかれた訳ではない。これもお菓子同様にゴミ箱行きだ。しかし、黒おばさんには赤の賄賂を見せつけておく必要があった。こうすれば、黒はもっと別の賄賂を持ってくるだろう。今度はこれが、私の新しい遊びになった。\n\n翌日、黒おばさんは商店街の五百円分の商品券を私に手渡した。赤おばさんはまたコンビニの引換券である。私は二つを見比べた。赤おばさんの引換券は、ポテトチップス一袋と引き換えができる。黒おばさんは五百円分の金券。私は金券を受け取って、黒おばさんを席に座らせた。\n\nこういったやり取りは、この後何度か続いた。自分のをなるべく痛めないように、かつ相手よりも価値で上回れるものを、おばさんたちは考えて私に比較をさせた。",
    "translation": "I compared the two. Red Bag’s coupon was for a bag of potato chips. Black Bag’s- three dollars at the mall. I took the three-dollar voucher and left my seat to Black Bag.\n\nThis exchange repeated itself countless times over the following weeks. Trying there damndest to not have to fork over any real cash, each lady tried to outfox the other with various gifts, after which they allowed me to compare them.\n\nBut this never went beyond an exchange of goods, it never got to the point where they were passing me cash.\n\nAfter we had reached this limit, I realized that it was impossible to scale up the operation any further.\n\nFrom then on, it would end up being the dull decision between a slew of bland and worthless knick-knacks which were all similar to one another.\n\nIf I wanted to see a new development, I had to take a new tact.\n\nOne day, when Black Bag boarded the bus, I noticed that she had a bug on her shoulder. It was a small thing- some sort of winged insect like a moth. She must have picked it up while standing at the bus stop. When they went to present the day’s bribes I didn’t take either. Instead, I reached up and plucked the bug off Black Bag’s shoulder with a tissue. Turning to her, I said, “Please sit here, miss.” And gave up my seat for her."
  },
  {
    "original": "しかし、これは物に留まって、直接的に現金を渡してくるには至らなった。この辺りで変化は終わりだろう。これからは似たり寄ったりのつまらない価値選択になる。もし新しいものが見たいなら、新しいことをしなくてはならない。\n\nある日、黒おばさんが肩に虫を乗せていた。ほんの小さなのような羽虫だ。きっとバス停待ちの際にでもついて、そのまま気づかず連れてきてしまったのだろう。私は二人がそれぞれ差し出すものではなく、黒おばさんの肩の蛾をティッシュでみ取り、それをもって黒おばさんに「どうぞ」と席を明け渡した。このことは、単純な有用性のから外れた法則不明のものに、二人には映ったに違いない。\n\nそれからというもの、おばさんたちはありとあらゆるもの、葉っぱや、本や、付きの、の、紅茶のティーバッグ、ハンカチなど、細々としているという共通項があるだけのものを次々と試した。\n\n私は、自分の欲しいものではなく、そして物品の内容にかかわらず、に「どうぞ」の先を決める。それを受けて、またおばさんたちのアプローチが変わる。今まで何が私に選ばれたのか、これから何が選ばれるのか。私は適当に決めているだけだというのに、傾向を必死に解釈しようとする様が哀れだった。",
    "translation": "This action must have, judging from how it affected the ladies afterward, had the effect of destabilizing the definition of “usefulness” that had been built into the bribe system originally.\n\nFrom then on in, I began to receive a myriad of items. Leaves, books, empty envelopes, shelled peanuts, bottle caps, black tea bags, handkerchiefs. The ladies continued to test out all sorts of minute trinkets that seemed to follow this new precedent.\n\nI did not personally want any of these items, and did not judge them on their inherent qualities, I was merely picking who I’d say “please sit her, miss” to arbitrarily.\n\nAnd upon receiving the seat, the bribes would evolve accordingly.\n\nWhat I had selected as a bribe up until now, and what would I deign to accept the next day?\n\nIn light of the fact that I was making these choices randomly, it was all the more pathetic seeing the ladies try to figure out the code with such enthusiasm.\n\n*\n\nOne day, while I was surveying the items the ladies had brought me as I always did, there came a sudden thud which sent a shimmer down the flooring of the bus.\n\nI looked down towards the front door to see what it was.\n\nAt that moment came the sound of another thud. The sound of something being thrust into the floor. After peering between the masses of bodies and clothing, I finally spied the old man who had been making the sound with his cane as he walked along."
  },
  {
    "original": "◆\n\n私がいつものように、おばさんたちの差し出す物品を検分していると、急にゴンと響く振動が床に伝わった。なにかと思って、人のから状況を窺う。するとまたゴンとなにかで床を突いている音がした。それから人の服と服の隙間に、老人が見えた。老人のが、床を突いていたのだ。乗り込んだ直後が一番大きな振動で、それからは小さな揺れが、老人が動くたびに床を走っている。\n\n老人は優先席の前に立ち止まった。明らかな社会的弱者だ。老いている上に、杖まで突いている。優先席のなかでも、最も優先されるべき一人。しかし、優先席を陣取るサラリーマンたちは居眠りのふりを続けていた。\n\n老人は席を譲られるべきだった。誰もいないのか、このなかに。少しでも老人より元気な人間は。そんなのは見た目だけでは分からないという。しかし、本当だろうか。優先席に座る五人が五人、本当に全員優先席が必要な人間なのだろうか。他の席の人はどうだ。老人に近い普通の席は。誰も、誰も譲らないのか。",
    "translation": "The biggest thud had come when he first got on the bus. And now small thuds rang down the flooring as the old man move down the lane.\n\nThe old man stopped in front of the seats reserved for the elderly and infirm – the priority seats.\n\nAny upstanding member of society would agree that he obviously fit the bill for both.\n\nHe was both old and sporting a cane.\n\nEven among the infirm, he would have received priority from most.\n\nBut the salary men who were sitting in the priority section, pretending to be asleep, did not move an inch as he stood there waiting.\n\nSomeone should have stepped up to give their seat to this man.\n\nTo this some would claim that you couldn’t tell who was infirm by sight.\n\nBut was this true?\n\nThere were 5 priority seats and 5 people in them, could all of them actually be in real need?\n\nWhat about the people in the other seats around the bus? The normal ones closest to the old man. No one. Not a single person would give up their seat.\n\nSomeone had to give up their seat for this man. And if the priority seats were full, then I would have to yield up my seat.\n\nI ignored the tributes of the ladies and raised my hand to touch the old man lightly on the shoulder."
  },
  {
    "original": "老人は席を譲られるべきだった。優先席がだめなら、私が譲るしかない。私はおばさんたちのぎ物を無視して手を伸ばし、老人の腕に軽く触れた。\n\n「ここ、よければどうぞ」\n\n老人はその言葉に反応して、無言で席に腰かけた。\n\n私はおばさんたちの衝撃を受けたような、その奥にをませるかな表情変化を楽しんだ。私は、この老人を助けたいから席を譲ったのではない。『社会的に』正しい行いだから席を譲ったのだ。別に老人のことなどは心底どうでもよかった。社会規範をある程度守らないと私の気がすまないというだけ。優先席に座りながら、席を譲らない人々など論外だ。社会の義務を放棄している。\n\nこのバスは人のさのりのようなものを積んでいる。私が正しくあらねばならないと思った。この醜さに染まらないために。一日くらいは、早めに席を立ってやってもよいだろう。",
    "translation": "“You can have my seat, if you like?”\n\nThe old man reacted to this by taking my now vacant seat quietly.\n\nIt felt as if I had received a sudden attack from the ladies, the slight change in emotional features which betrayed an underlying disappointment- which I relished.\n\nI didn’t give up my seat out of an urge to help the old man.\n\nI gave up my seat because it was the upstanding thing to do.\n\nTo me, deep down, the old man meant absolutely nothing to me. I merely have a knee jerk reaction to adhere to the societal values that have been engrained into me. Someone sitting in a priority seat who is not willing to yield it up if need be…that is totally out of the question. Such a person is shirking their duty to everyone else.\n\nThis bus seemed to be packed with a collection of congealed human filth. And in that situation, I thought I had to do what was right. If only to not be tainted by everyone else’s ugliness. It was just for a day. It was the least I could do to stand up a bit early and bide my time until my own stop.\n\nBut this was not the end of it. The old man started to use this bus every day from then onward.\n\nWhat was worse, instead of attempting to sit in the priority seat each day, he would approach and stand directly in front of me. And because he got on at the same stop as Red Bag and Black Bag, either one of them could have seized their chance and sat in my open seat before the old man had the chance to."
  },
  {
    "original": "しかし、それでは終わらなかった。老人はそれから毎日この同じ時間のバスを利用するようになった。しかも、優先席ではなく必ず私の前に立って。おばさんたちと同じバス停で乗り込んでくるため、私が席を立ったとき、おばさんなら老人の代わりにここに座ることができただろうに、おばさんのしさも、この弱者の前には歯が立たないようだった。老人からは、くらくらするほどのがした。甘い腐敗と死のい。きっと人は生きながらに段々と細胞が腐っていく。この嫌悪感はど死へのと言って良かった。他の乗客は当然のように知らんぷりを決めて、自分の席からは動かない。\n\n私はに我慢がならず、この日老人が乗ってきても眠ったふりをして席を譲らなかった。優先席の他の人、いては私の隣に座るお前が席を譲ってくれと願って。しかし、老人はあろうことかそんな私の脚を杖でつついた。私はこの老人に一度席を譲ってしまったことをしていた。",
    "translation": "But it seemed that both of their plotting nature’s no longer had teeth in the face of the frail specimen the man posed.\n\nThe old man gave off the sort of smell that only truly old people do.\n\nThe smell of sweet decay and death.\n\nIt’s a simple truth. As humans live and age, their cells gradually start to rot away.\n\nPerhaps the disgust I-we (as busgoers) felt was some sort of repellent that we were all trying to use to shield us from death.\n\nThe other riders, as if it was obvious, chose to ignore the smell. And more importantly, they proceeded to not give up their seats.\n\nEventually, I couldn’t put up with it anymore and pretended to be asleep the next time the old man boarded the bus.\n\nI hoped that a person in the priority seat section would give up their seat, or at the very least you sitting next to me would be inspired enough to give up yours.\n\nBut the old man seemed to take umbrage with this and wrapped my leg with his cane. I was full of regret that I had ever given up my seat to this old guy in the first place.\n\n*\n\nThe next day, the ladies found me standing, grabbing the safety straps, and seemed to be scanning me slightly."
  },
  {
    "original": "◆\n\n次の日、おばさんは立ってつり革を摑んでいる私を見つけて、僅かに目を見張った。\n\nでも、もうおばさんにも関係ないはずだ。結局あの席には老人が座ることになったのだから。\n\n私は初めから座席には座らないことにした。初めからこうするべきだった。これでやっと全員が不幸になれる。\n\n始発から乗る私は、席に座らずつり革を摑む。席はあっという間に埋まっていった。その様子を私はただ立って眺める。もう途中下車する人間はいなくなり、空席も生まれない。乗り込んできた二人のおばさんは、そのまま諦めたように私の隣のつり革を摑んだ。\n\n老人が来た。杖の音がゴンと響く。誰も席を譲ろうとはしない。優先席も、その他の人も、誰一人として。老人は立っている私の姿を認めて、怒りの表情を向けた。私はそれに応えてむ。\n\n扉が空気圧の音を立てて閉まった。私たち全員は横並びになって一様にバスに揺られた。車内はひどく蒸している。\n\n【おわり】",
    "translation": "But my relationship with the ladies was already over. Because that seat had now been turned over to the old man.\n\nToday, I had decided not to sit down at all.\n\nPerhaps, I should have just done this from the beginning.\n\nAnd now perhaps we could all just be unhappy together.\n\nGetting on at the first stop of the bus, I grabbed the safety handle. The open seats seem to disappear in a blink as the bus completed the first part of its route.\n\nI saw it all happen as I stood there.\n\nIn the middle of the route. There was no longer anyone who was trying to get off anymore, and free seats no longer cropped up here and there.\n\nAs for the two ladies, they boarded the bus and took their positions beside me holding their own safety straps-looks of resignation on their faces.\n\nThe old man came by next.\n\nThe sound of his cane reverberated through the bus.\n\nNobody gave up their seat for him. Not from the priority seating area nor the regular seats, not a single person.\n\nThe old man seemed to recognize me and flashed an angry glare in my direction.\n\nWhich I responded to with a smile.\n\nThe door of the bus closed with a hydraulic spurt of sound. We were- all of us- lined up and shaking equitably along with the bus.\n\nAnd the interior of the bus was as muggy as ever.\n\n(The End)"
  },

];
