// The remote library feed has no publisher field, so keep the Skyhorse catalog
// explicit. This list combines the verified retailer records with confirmed
// Skyhorse titles that do not yet have retailer links here.
export const SKYHORSE_CATALOG_BOOK_IDS = new Set([
  "a-horse-for-elsie",
  "acts-of-allegiance",
  "becky-meets-her-match",
  "cowboys",
  "fighting-techniques-of-the-elite-forces",
  "fire-in-the-night",
  "framed-in-monte-carlo",
  "home-is-where-the-heart-is",
  "hope-deferred",
  "hope-on-the-plains",
  "i-am-the-storm",
  "i-will",
  "imperfect-solo",
  "innovators",
  "judgment-in-berlin",
  "killing-kennedy",
  "kremlin-wives",
  "lincoln-and-the-irish",
  "little-book-of-restorative-teaching-tools",
  "love-in-unlikely-places",
  "mala-vida",
  "napoleon-a-biography",
  "nine-scorpions-in-a-bottle",
  "people-of-the-first-crusade",
  "pigs-of-paradise",
  "political-assassinations-and-attempts-in-us-history",
  "real-irish-new-york",
  "return-from-siberia",
  "running-around-and-such",
  "scottish-miscellany",
  "sky-ranch",
  "the-generals-cook",
  "the-golden-age-of-pirates",
  "the-homestead",
  "the-last-imperialist",
  "the-pasha-of-cuisine",
  "the-truth-about-the-oj-simpson-trial",
  "the-young-hitler-i-knew",
  "we-the-women",
]);

// Keep this narrower set for license attribution on audiobook landing pages.
export const SKYHORSE_LICENSED_BOOK_IDS = new Set([
  "killing-kennedy",
  "the-homestead",
  "cowboys",
  "scottish-miscellany",
  "people-of-the-first-crusade",
  "the-pasha-of-cuisine",
  "innovators",
  "judgment-in-berlin",
  "lincoln-and-the-irish",
  "running-around-and-such",
  "a-horse-for-elsie",
]);
